CMAINXX       MAINXX/COLPROB - BARILOCHE 1979
C
C ADMINISTRATIVE ROUTINE OF THE PROGRAM COLPROB. THE PROGRAM SHOWS THE
C USE OF FIRST-FLIGHT COLLISION PROBABILITIES TO CALCULATE THE FLUX IN
C AN ANNULAR SYSTEM OF MMAX CONCENTRIC SHELLS.
C
C SUBROUTINES NEEDED:
C   1) PREPAR - READING GEOMETRIC AND XS DATA, PREPARING CERTAIN ARRAYS.
C               IT ALSO PRODUCES AN EDIT OF THE INPUT DATA.
C   2) COPRAN - FINDING FIRST-FLIGHT COLLISION PROBABILITIES AND PARTIAL
C               BLACKNESSES IN A SYSTEM OF MMAX CONCENTRIC SHELLS WITH A
C               BLACK OUTER BOUNDARY. THE METHOD OF I. CARLVIK IS USED,
C               WITH AN IG-POINT GAUSS-JACOBI INTEGRATION OVER TH THICK-
C               NESS OF EACH SHELL.
C   3) KI3    - EVALUATES BICKLEY FUNCTION KI3(X), NEEDED BY COPRAN.
C   4) GAUSCP - SETS UP AND INVERTS THE SOLUTION MATRIX FOR THE RESPONSE
C               FLUXES.
C   5) CALFLU - READS SOURCE DISTRIBUTION AND EXTERNAL INCIDENT CURRENT,
C               EVALUATES TOTAL FLUXES AND PARTIAL CURRENTS, PRINTS THE
C               RESULTS.
C
      COMMON / CPR000 / A(1000)
      COMMON / CPR001 / NIN, NOT, NX1(2)
      COMMON / CPR002 / MMAX, IG, NX2(4)
C
 1010 FORMAT(2I6)
 2010 FORMAT(/18H REQUIRED MEMORY (,I4,15H) IS TOO LARGE./
     1       54H ADJUST SIZE OF A() IN COMMON/CPR000/ IN MAIN ROUTINE.)
C
C READ DIMENSION DATA. A BLANK CARD TERMINATES THIS RUN.
C
      NIN = 5
      NOT = 6
   10 READ(NIN, 1010) MMAX, IG
      IF(MMAX.EQ.0) STOP
C
C ADDRESSING.
C
      LRAD  = 1
      LVOL  = LRAD  + MMAX
      LSIG  = LVOL  + MMAX
      LSIGS = LSIG  + MMAX
      LSIGR = LSIGS + MMAX
      LSIG1 = LSIGR + MMAX
      LSEC  = LSIG1 + MMAX
      LSIGV = LSEC  + MMAX
C
      LP     = LSIGV + MMAX
      LGAM   = LP    + MMAX*MMAX
      LYI    = LGAM
      LXIK   = LYI  + MMAX
      LQI    = LXIK + MMAX*MMAX
      LVOLY  = LQI  + MMAX
      LFLUXQ = LVOLY
      LFLUJ  = LFLUQ + MMAX
      LFLUX  = LFLUJ + MMAX
      LREMO  = LFLUX + MMAX
      LAST   = LREMO + MMAX
C
      IF(LAST.LE.1000) GO TO 20
      WRITE(NOT, 2010) LAST
      STOP
C---------------------------------------------------------------
   20 CALL PREPARE(A(LRAD), A(LVOL), A(LSIG), A(LSIGS), A(LSIGR),
     1            A(LSIG1), A(LSEC), A(LSIGV))
      CALL COPRAN(MMAX, IG, A(LRAD), A(LSIG), A(LP), A(LGAM))
      WRITE(NOT,*)
      WRITE(NOT,*) A(LP), A(LP+1), A(LP+2), A(LP+3)
      WRITE(NOT,*)
      WRITE(NOT,*) A(LP+4), A(LP+5), A(LP+6), A(LP+7)
      WRITE(NOT,*)
      WRITE(NOT,*) A(LP+8), A(LP+9), A(LP+10), A(LP+11)
      WRITE(NOT,*)
      WRITE(NOT,*) A(LP+12), A(LP+13), A(LP+14), A(LP+15)
      WRITE(NOT,*)
      CALL GAUSCP(MMAX, A(LSEC), A(LSIG1), A(LISGV), A(LP),
     1            A(LGAM), A(LXIK))
      CALL CALFLU(MMAX, A(LVOL), A(LSIGR), A(LYI), A(LXIK),
     1            A(LQI), A(LVOLY), A(LFLUQ), A(LFLUJ), A(LFLUX),
     2            A(LREMO))
C---------------------------------------------------------------
      GO TO 10
      END