name: Build and Test

on:
  push:
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest scikit-build-core numpy

      - name: Install system dependencies (X11, OpenMP, OpenGL)
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libx11-dev \
            libxrandr-dev \
            libxinerama-dev \
            libxcursor-dev \
            libxi-dev \
            libomp-dev \
            mesa-common-dev \
            libgl1-mesa-dev \
            libglu1-mesa-dev

      - name: Build CMake project
        run: |
          mkdir -p build
          cd build
          cmake .. -DCMAKE_BUILD_TYPE=Release
          cmake --build . --config Release

      - name: Run Python tests with pytest
        run: |
          export PYTHONPATH=$PWD/build:$PYTHONPATH
          pytest tests/
