name: Build and Test

on:
  push:
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

       #Setup Python
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'  #Can be changed

      #Install dependencies
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest scikit-build-core numpy

      #Build
      - name: Build CMake project
        run: |
          mkdir -p build
          cd build
          cmake .. -DCMAKE_BUILD_TYPE=Release
          cmake --build . --config Release

      #Set PYTHONPATH to point to build output (so Python can find _scarabee)
      - name: Run Python tests with pytest
        run: |
          export PYTHONPATH=$PWD/build:$PYTHONPATH
          pytest tests/
