name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build-and-test:
    name: Build & Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-13, macos-14]

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install scikit-build-core numpy pytest pytest-check pytest-timeout pytest-xdist scipy

      - name: Install system deps (Ubuntu)
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libx11-dev libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev \
            libomp-dev mesa-common-dev libgl1-mesa-dev libglu1-mesa-dev

      - name: CMake configure & build
        run: |
          cmake -S . -B build
          cmake --build build --config Release

      - name: Install Python module
        run: |
          python -m pip install .

      - name: Run pytest suite
        run: |
          pytest tests/

